#!/bin/bash

osascript <<'EOF'

set tab1Dir to "/Users/ludell/Documents/Privat/prosjekter/godtur/godtur_api"
set tab2Dir to "/Users/ludell/Documents/Privat/prosjekter/godtur/godtur_api"
set tab3Dir to "/Users/ludell/Documents/Privat/prosjekter/godtur/godtur_weather_api"
set tab4Dir to "/Users/ludell/Documents/Privat/prosjekter/godtur/godtur_weather_api"
set tab5Dir to "/Users/ludell/Documents/Privat/prosjekter/godtur/godtur_web_two"
set tab6Dir to "/Users/ludell/Documents/Privat/prosjekter/godtur/godtur_web_two"

tell application "Ghostty"
    activate

    -- Tab 1
    set cfg1 to new surface configuration
    set initial working directory of cfg1 to tab1Dir
    set win to new window with configuration cfg1
    delay 0.3
    set term to focused terminal of selected tab of win
    perform action "set_tab_title:API" on term

    -- Tab 2
    set cfg2 to new surface configuration
    set initial working directory of cfg2 to tab2Dir
    set t2 to new tab in win with configuration cfg2
    delay 0.3
    perform action "set_tab_title:API" on focused terminal of t2

    -- Tab 3
    set cfg3 to new surface configuration
    set initial working directory of cfg3 to tab3Dir
    set t3 to new tab in win with configuration cfg3
    delay 0.3
    perform action "set_tab_title:Weather-API" on focused terminal of t3

    -- Tab 4
    set cfg4 to new surface configuration
    set initial working directory of cfg4 to tab4Dir
    set t4 to new tab in win with configuration cfg4
    delay 0.3
    perform action "set_tab_title:Weather-API" on focused terminal of t4

    -- Tab 5
    set cfg5 to new surface configuration
    set initial working directory of cfg5 to tab5Dir
    set t5 to new tab in win with configuration cfg5
    delay 0.3
    perform action "set_tab_title:Frontend" on focused terminal of t5

    -- Tab 6
    set cfg6 to new surface configuration
    set initial working directory of cfg6 to tab6Dir
    set t6 to new tab in win with configuration cfg6
    delay 0.3
    perform action "set_tab_title:Frontend" on focused terminal of t6

    -- Focus the first tab
    select tab (tab 1 of win)
end tell
EOF