name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. 1.0.0). Don't include the 'v' prefix, it will be added automatically."
        required: true

permissions:
  contents: write

jobs:
  release:
    if: github.actor == 'ljellevo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create release
        uses: softprops/action-gh-release@c062e08bd532815e2082a7e09ce9571a6d1eeaf4 # v2.2.1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          files: |
            ghostab
            install.sh
